import React, { useRef } from 'react';
import html2pdf from 'html2pdf.js';
import { api } from '../../services/api';
import { BudgetChart } from './BudgetChart';
import { RiskMatrixChart } from './RiskMatrixChart';
import { Download, Sparkles, ShieldCheck, FileCheck, CheckCircle2, Award, Calendar, DollarSign } from 'lucide-react';

export const ExecutiveReportView = ({ simulationData }) => {
  const reportRef = useRef(null);

  if (!simulationData || !simulationData.report) {
    return (
      <div className="glass-panel p-12 text-center text-slate-400 font-mono">
        No executive report available. Please run a boardroom simulation first.
      </div>
    );
  }

  const { simulation, agent_decisions, report } = simulationData;

  const handleDownloadPDF = () => {
    const element = reportRef.current;
    const opt = {
      margin: [10, 10, 10, 10],
      filename: `Executive_Board_Report_${simulation.id}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, backgroundColor: '#030712' },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };
    html2pdf().set(opt).from(element).save();
  };

  return (
    <div className="w-full space-y-6">
      {/* Top Action Header */}
      <div className="flex items-center justify-between glass-panel p-4 rounded-2xl border border-white/10">
        <div>
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            Executive Strategy Briefing
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
              BOARD APPROVED
            </span>
          </h2>
          <p className="text-xs text-slate-400 font-mono">Generated by ShadowBoard Enterprise AI Engine</p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={async () => {
              try {
                const goal = simulation.goal || 'Special Sale';
                const text = goal.toLowerCase();
                const discountMatch = text.match(/(\d+)\s*%/);
                const discountPercentage = discountMatch ? parseInt(discountMatch[1]) : 40;

                let title = '⚡ FESTIVAL MEGA SALE';
                let promoCode = `FESTIVAL-SHADOW${discountPercentage}`;
                let occasionKey = 'seasonal';

                if (text.includes('dussehra') || text.includes('dasara')) {
                  title = '🏹 DUSSEHRA FESTIVAL CELEBRATION';
                  promoCode = `DUSSEHRA-${discountMatch ? 'SHADOW' + discountPercentage : 'PROFIT35'}`;
                  occasionKey = 'dussehra';
                } else if (text.includes('christmas') || text.includes('xmas')) {
                  title = '🎄 CHRISTMAS HOLIDAY SALE';
                  promoCode = `XMAS-${discountMatch ? 'SHADOW' + discountPercentage : 'PROFIT35'}`;
                  occasionKey = 'christmas';
                } else if (text.includes('black friday')) {
                  title = '🛍️ BLACK FRIDAY CYBER SALE';
                  promoCode = `BLACKFRIDAY-${discountMatch ? 'SHADOW' + discountPercentage : 'PROFIT35'}`;
                  occasionKey = 'blackfriday';
                } else if (text.includes('new year')) {
                  title = '🎆 NEW YEAR CELEBRATION SALE';
                  promoCode = `NEWYEAR-${discountMatch ? 'SHADOW' + discountPercentage : 'PROFIT35'}`;
                  occasionKey = 'newyear';
                } else if (text.includes('diwali') || text.includes('deepavali')) {
                  title = '🪔 DIWALI FESTIVAL OF LIGHTS SALE';
                  promoCode = `DIWALI-${discountMatch ? 'SHADOW' + discountPercentage : 'PROFIT35'}`;
                  occasionKey = 'diwali';
                } else {
                  const saleMatch = goal.match(/(?:launch|run|start|create)?\s*(?:a|an)?\s*([a-zA-Z0-9\s]+(?:sale|campaign|offer|discount|promo))/i);
                  const name = saleMatch ? saleMatch[1].trim().toUpperCase() : 'SPECIAL MEGA SALE';
                  title = `⚡ ${name}`;
                  promoCode = `${name.replace(/[^A-Z0-9]/g, '').substring(0, 10)}-PROFIT35`;
                  occasionKey = 'seasonal';
                }

                await api.deployCampaign({
                  title,
                  discountPercentage,
                  promoCode,
                  bannerText: `SPECIAL CELEBRATION • ${discountPercentage}% OFF ACROSS ALL CATEGORIES!`,
                  marketingSpend: simulation.marketing_spend || '₹50 Lakhs',
                  occasionKey,
                  simulationId: simulation.id
                });
                window.open('/demo-store', '_blank');
              } catch (err) {
                alert('Failed to deploy to store: ' + err.message);
              }
            }}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 via-rose-500 to-purple-600 font-extrabold text-xs text-black shadow-[0_0_25px_rgba(245,158,11,0.4)] hover:opacity-95 transition-all animate-pulse"
          >
            <Sparkles className="w-4 h-4 fill-current text-black" />
            <span>🚀 DEPLOY TO LIVE DEMO WEBSITE</span>
          </button>

          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-xs font-bold text-white shadow-xl hover:opacity-90 transition-all"
          >
            <Download className="w-4 h-4" />
            <span>Download Executive PDF</span>
          </button>
        </div>
      </div>

      {/* PDF Target Container */}
      <div ref={reportRef} className="glass-panel p-8 rounded-3xl border border-white/10 space-y-8 text-slate-100 bg-[#030712]">
        {/* Document Header */}
        <div className="border-b border-white/10 pb-6 flex items-start justify-between">
          <div>
            <div className="text-xs font-mono text-cyan-400 tracking-widest uppercase mb-1">
              SHADOWBOARD ENTERPRISE AI • STRATEGIC MEMORANDUM
            </div>
            <h1 className="text-xl font-extrabold text-white">{simulation.title || simulation.goal}</h1>
            <div className="flex items-center gap-4 text-xs font-mono text-slate-400 mt-2">
              <span>Date: {new Date(simulation.created_at || Date.now()).toLocaleDateString()}</span>
              <span>Target: {simulation.location}</span>
              <span>Budget: {simulation.budget}</span>
            </div>
          </div>
          <div className="w-12 h-12 rounded-2xl bg-indigo-600/20 border border-indigo-500/40 flex items-center justify-center text-cyan-400 font-bold">
            AI
          </div>
        </div>

        {/* KPI Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <div className="text-[10px] font-mono text-slate-400">ESTIMATED ROI</div>
            <div className="text-lg font-extrabold text-emerald-400 mt-1">{report.roi_projection || '285% (24 Mo)'}</div>
          </div>
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <div className="text-[10px] font-mono text-slate-400">RISK INDEX</div>
            <div className="text-lg font-extrabold text-amber-400 mt-1">{report.risk_score || 34} / 100</div>
          </div>
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <div className="text-[10px] font-mono text-slate-400">TIMELINE HORIZON</div>
            <div className="text-lg font-extrabold text-indigo-400 mt-1">{simulation.timeline}</div>
          </div>
          <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800">
            <div className="text-[10px] font-mono text-slate-400">STAFF COMMITMENT</div>
            <div className="text-lg font-extrabold text-cyan-400 mt-1">{simulation.employees} Employees</div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800">
          <h3 className="text-xs font-mono font-bold text-indigo-300 uppercase tracking-wider mb-2 flex items-center gap-2">
            <FileCheck className="w-4 h-4 text-indigo-400" />
            Executive Summary
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed font-sans">{report.executive_summary}</p>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800">
            <h3 className="text-xs font-mono font-bold text-cyan-300 uppercase tracking-wider mb-4">
              Capital Budget Allocation
            </h3>
            <BudgetChart data={report.budget_breakdown} />
          </div>

          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800">
            <h3 className="text-xs font-mono font-bold text-rose-300 uppercase tracking-wider mb-4">
              Risk Matrix Analysis
            </h3>
            <RiskMatrixChart riskScore={report.risk_score} />
          </div>
        </div>

        {/* Departmental Decisions Table */}
        <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800">
          <h3 className="text-xs font-mono font-bold text-emerald-300 uppercase tracking-wider mb-4">
            Departmental Mandates & Decisions
          </h3>
          <div className="space-y-3">
            {agent_decisions &&
              agent_decisions.map((agent, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-slate-900/90 border border-slate-800 text-xs">
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-bold text-white">{agent.agent_name}</span>
                    <span className="text-[10px] font-mono text-cyan-400">{agent.confidence}% Confidence</span>
                  </div>
                  <p className="text-slate-300 text-xs">{agent.decision}</p>
                </div>
              ))}
          </div>
        </div>

        {/* Milestones Roadmap */}
        {report.milestones && (
          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800">
            <h3 className="text-xs font-mono font-bold text-purple-300 uppercase tracking-wider mb-4">
              Execution Roadmap & Milestones
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {report.milestones.map((m, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-slate-900 border border-slate-800 text-xs">
                  <span className="text-[10px] font-mono text-indigo-400 font-bold uppercase">{m.phase}</span>
                  <h4 className="font-bold text-white mt-1 mb-1">{m.title}</h4>
                  <p className="text-slate-400 text-xs">{m.detail}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* CEO Final Recommendation */}
        <div className="p-6 rounded-2xl bg-gradient-to-r from-indigo-950/80 to-purple-950/80 border border-indigo-500/50 shadow-xl">
          <h3 className="text-xs font-mono font-bold text-cyan-300 uppercase tracking-wider mb-2 flex items-center gap-2">
            <Award className="w-4 h-4 text-cyan-400" />
            Final CEO Board Recommendation
          </h3>
          <p className="text-sm font-semibold text-white leading-relaxed">{report.final_recommendation}</p>
        </div>
      </div>
    </div>
  );
};
